### ISSUE TITLE
Home画面の画像表示ずれ

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1708#111]

**Comment by taxio** [comment]
<img width="1401" alt="2017-11-10 23 52 42" src="https://user-images.githubusercontent.com/15796172/32663809-9cfbfd1a-c672-11e7-9500-9eba75805191.png">

**Comment by pddg** [comment]
templateのifの位置がおかしい．

**Comment by tatsuya1407** [comment]
詳しく書いてほしい…

**Comment by pddg** [comment]
もう修正した

**Comment by tatsuya1407** [comment]
ありがとう！
