### ISSUE TITLE
UI改善

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1708#57]

**Comment by taxio** [comment]
11/6(月)夜までにUI改善案を提出

**Comment by pddg** [comment]
* トップ画面におけるチェックボックス押しづらい問題
* 科目詳細画面や問題画面が適当すぎる問題
* 全体的に体裁を整えないとダメ問題

**Comment by AkiraMAEGAWA** [comment]
UI改善案(11/6の朝)
1.  チェックボックスが小さい問題
    * チェックボックスをなくして、画像を直接選択するようにする。
      * 選択されているものは太枠などで分かるように。
      * 画像のチェックボックスだけでなく、科目名のやつも背景色を変えて選択が分かるように
      * 左上に、選択されていることを示す"✓"アイコンとか付けると分かりやすいかも(optional)
    * もしくはチェックボックスを残しつつ、画像を選択選択できるようにする

2. 科目詳細画面と問題画面が適当問題
    * 科目詳細画面
      * 時系列が把握し安くするために、予め一週間分のテーブルを用意する
        * 現状は、科目を追加すると下に挿入されていくから分かりにくい
        * 追加した科目は、そのテーブルの対応する所に表示
    * 問題作成画面
      * 問題作成に使うキーワードを、箇条書き等で表示する
        * 現状は、キーワードごととか関係なく表示されていて、どこまでが1つのキーワードか分からない
      *  問題作成ボタンの位置をさらに強調して表示
        * 例えば科目名を保持しているdivタグの上下どちらか

3. 全体的に体裁を整える
    * 右上の" Home Lectures Tasks CaptureNow"にフリーのアイコンを加える
      * 例えばHomeには家のアイコン、CaptureNowにはカメラアイコン等
    * Homeのページで、"保存"を"追加"に変更する
      * 追加のほうが、画像を科目に加える感がある
    * 画像の下に書いてある時間表示を直す
      * 情報として正しいけど見にくい
    * CaptureNow押下後のキャリブレーションを"OK"ではなく"授業開始"等に変更
      * "OK"ではキャリブレーションができたことは分かるがキャプチャ開始が分からない
    * Task画面なんとかしたい

**Comment by AkiraMAEGAWA** [comment]
後で、画像で説明する

**Comment by tatsuya1407** [comment]
<img width="881" alt="ui _lecture" src="https://user-images.githubusercontent.com/23404044/32435929-c6b53784-c325-11e7-8112-c6cd052b7224.png">
<img width="877" alt="ui _home" src="https://user-images.githubusercontent.com/23404044/32435930-c6f0c24a-c325-11e7-830b-bb2d2f87a3d5.png">

**Comment by tatsuya1407** [comment]
とりあえず大雑把なUI改善案(Home,Lecture画面)です。

**Comment by tatsuya1407** [comment]
・Home
image選択せずにlectureに紐づけて保存でエラー
webcameraに接続せずにcapturenowでエラー
