### ISSUE TITLE
細かい文言の変更

### ISSUE THREAD

**Issue by pddg** [jphacks/KB_1708#70]
* [ ] 右上の" Home Lectures Tasks CaptureNow"にフリーのアイコンを加える
    * 例えばHomeには家のアイコン、CaptureNowにはカメラアイコン等
* [ ] Homeのページで、"保存"を"追加"に変更する
    *追加のほうが、画像を科目に加える感がある
* [ ] 画像の下に書いてある時間表示を直す
    * 情報として正しいけど見にくい
* [ ] CaptureNow押下後のキャリブレーションを"OK"ではなく"授業開始"等に変更
    * "OK"ではキャリブレーションができたことは分かるがキャプチャ開始が分からない
* [ ] Task画面なんとかしたい

**Comment by taxio** [comment]
fixed by #109
