### ISSUE TITLE
キャリブレーションの改善

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1708#72]
[参考](https://geekduck.github.io/getUserMedia/)

**Comment by taxio** [comment]
https://github.com/opencv/opencv/issues/6308

**Comment by pddg** [comment]
http://otiai10.hatenablog.com/entry/2017/01/12/123851

**Comment by pddg** [comment]
https://geekduck.github.io/getUserMedia/

**Comment by taxio** [comment]
fixed by #93
