### ISSUE TITLE
問題生成アルゴリズム

### ISSUE THREAD

**Issue by taxio** [jphacks/KB_1708#9]

**Comment by AkiraMAEGAWA** [comment]
どんな問題がいいかを適当にあげていく。

* 〇〇の定義を答えよ。　whatIs
* 〇〇を計算せよ。  calculate
* 〇〇を説明せよ。  explain
* 〇〇を考案したのは誰か？ whoDidCreate
* 〇〇の類語を答えよ   tellSynonymOf
* 〇〇
* 〇〇
